options:
  enable-metadata:
    type: boolean
    default: True
    description: Set as True to enable metadata support
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
  plumgrid-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of plumgrid-pythonlib package that needs to be installed
  networking-build:
    type: string
    default:
    description: |
       Provide the build version of networking-plumgrid package that needs to be installed.
       Accepted values are either 'latest' (which installs latest networking-plumgrid
       package available) or a specific version for the package.
  networking-plumgrid-version:
    default: null
    type: string
    description: |
       Provide the version of networking-plumgrid package that needs to be installed
  hardware-vendor-name:
    type: string
    default: vendor_name
    description: Name of the supported hardware vendor
  switch-username:
    type: string
    default: plumgrid
    description: Username of the L2 gateway
  switch-password:
    type: string
    default: plumgrid
    description: Password of the L2 gateway
  manage-neutron-plugin-legacy-mode:
    type: boolean
    default: True
    description: |
      If True neutron-api charm will install neutron packages for the plugin
      configured. Also needs to be set in neutron-api charm
  connector-type:
    type: string
    default: distributed
    description: |
      Type of connector to be used. Supported types are 'distributed' and 'service'
  pip-proxy:
    type: string
    default: None
    description: |
      Proxy address to install python modules behind a proxy
  user-domain-name:
    type: string
    default: Default
    description: Keystone user domain name
  project-domain-name:
    type: string
    default: Default
    description: Keystone project domain name
  enable-deb-networking-install:
    type: boolean
    default: False
    description: |
      If enabled networking plumgrid is installed from deb package on LCM instead of
      installation using pip
  enable-flow-tap:
    type: boolean
    default: True
    description: Toggles reverse flow creation for tap based policies
  enable-metaconfig:
    type: boolean
    default: True
    description: Enables/disables nova communication for metaconfig
